/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package e.commerce;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingWorker;
/**
 *
 * @author huzai
 */
public final class UserHomePage extends javax.swing.JFrame {
    private String UID,Keyword,sort,filter;
 JpanelLoader load = new JpanelLoader();
  Connection connection = DatabaseConnectivity.getConnection();
 
 
  

  
  Login li=new Login();
 
    /**
     * Creates new form UserHomePage
     */
    public UserHomePage(String userID) {
        UID=userID;
      
        initComponents();
          if(UID!="0"){//hiding loginbutton if user is already loggedIn (Raffay)
            jButton2.setVisible(false);
         worker.execute();
        }
        
         
  
 Loader2.setVisible(false);
  HomePanel hp=new HomePanel(UID,Keyword,sort,filter);
       load.jPanelLoader(Loader, hp);
//       load.jPanelLoader(Loader2, category);
         setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        setExtendedState(this.MAXIMIZED_BOTH);
      
    }
      SwingWorker<Void, Integer> worker = new SwingWorker<Void, Integer>() {
        @Override
        protected Void doInBackground() throws Exception {
            // Simulate a task by updating progress in a loop
            for (int i = 0; i <= 30; i++) {
                Thread.sleep(25); // Simulate time-consuming task
                publish(i); // Publish progress
            }
               handleNotifications();
            return null;
        }};
public void handleNotifications() {
    try {
        // Retrieve all order numbers from the notifications table
        List<Integer> orderNumbers = getOrderNumbers();

        // Prepare the message for JOptionPane
        StringBuilder message = new StringBuilder();
        int totalOrders = orderNumbers.size();
        if (totalOrders == 0) {
        } else {
            // Construct the message based on the number of orders delivered
            message.append("Your order number");
            if (totalOrders > 1) {
                message.append("s"); // Plural if more than one order
            }
            message.append(": ");
            for (int i = 0; i < totalOrders; i++) {
                message.append(orderNumbers.get(i));
                if (i < totalOrders - 1) {
                    message.append(", ");
                }
            }
            message.append(" ").append(totalOrders > 1 ? "have" : "has").append(" been delivered.");
            JOptionPane.showMessageDialog(null, message.toString());
        }

        // Show a JOptionPane message containing the order numbers
        

        // Update the notificationSent column for those notifications
        updateNotificationSent(orderNumbers);
    } catch (Exception e) {
        e.printStackTrace();
    }
}
private List<Integer> getOrderNumbers() throws SQLException {
        List<Integer> orderNumbers = new ArrayList<>();
        String query = "SELECT OrderID FROM notifications WHERE notificationSent = 0";
        try (PreparedStatement statement = connection.prepareStatement(query);
             ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                int orderID = resultSet.getInt("OrderID");
                orderNumbers.add(orderID);
            }
        }
        return orderNumbers;
    }

    // Method to update the notificationSent column for those notifications
    private void updateNotificationSent(List<Integer> orderNumbers) throws SQLException {
        String updateQuery = "UPDATE notifications SET notificationSent = 1 WHERE OrderID = ?";
        try (PreparedStatement statement = connection.prepareStatement(updateQuery)) {
            for (int orderNumber : orderNumbers) {
                statement.setInt(1, orderNumber);
                statement.addBatch();
            }
            statement.executeBatch();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();
        Loader2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        HomeBtn = new javax.swing.JToggleButton();
        ManageAccountBtn = new javax.swing.JToggleButton();
        CartBtn = new javax.swing.JToggleButton();
        MyOrderBtn = new javax.swing.JToggleButton();
        MyReviewsbtn = new javax.swing.JToggleButton();
        MyWishListBtn = new javax.swing.JToggleButton();
        Loader = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logo-removebg-preview.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 19)); // NOI18N
        jLabel2.setText("BROWSEBAZAR");

        jComboBox2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filter by Rating", "Rating 5", "Rating 4 and above", "Rating 3 and above" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort by Price", "Price Low to high", "Price High to low " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField2.setText("Search Products");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setText("Cart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        Loader2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Loader2FocusGained(evt);
            }
        });
        Loader2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Loader2MouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel4FocusGained(evt);
            }
        });

        HomeBtn.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(HomeBtn);
        HomeBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        HomeBtn.setForeground(new java.awt.Color(255, 255, 255));
        HomeBtn.setText("Home");
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });

        ManageAccountBtn.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(ManageAccountBtn);
        ManageAccountBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ManageAccountBtn.setForeground(new java.awt.Color(255, 255, 255));
        ManageAccountBtn.setText("Manage Account");
        ManageAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAccountBtnActionPerformed(evt);
            }
        });

        CartBtn.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(CartBtn);
        CartBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CartBtn.setForeground(new java.awt.Color(255, 255, 255));
        CartBtn.setText("Cart");
        CartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartBtnActionPerformed(evt);
            }
        });

        MyOrderBtn.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(MyOrderBtn);
        MyOrderBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MyOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        MyOrderBtn.setText("My Orders");
        MyOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyOrderBtnActionPerformed(evt);
            }
        });

        MyReviewsbtn.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(MyReviewsbtn);
        MyReviewsbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MyReviewsbtn.setForeground(new java.awt.Color(255, 255, 255));
        MyReviewsbtn.setText("My Reviews");
        MyReviewsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyReviewsbtnActionPerformed(evt);
            }
        });

        MyWishListBtn.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(MyWishListBtn);
        MyWishListBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MyWishListBtn.setForeground(new java.awt.Color(255, 255, 255));
        MyWishListBtn.setText("My Wishlist");
        MyWishListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyWishListBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ManageAccountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CartBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MyOrderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MyReviewsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MyWishListBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ManageAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MyOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MyReviewsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MyWishListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Loader2Layout = new javax.swing.GroupLayout(Loader2);
        Loader2.setLayout(Loader2Layout);
        Loader2Layout.setHorizontalGroup(
            Loader2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Loader2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Loader2Layout.setVerticalGroup(
            Loader2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Loader2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout LoaderLayout = new javax.swing.GroupLayout(Loader);
        Loader.setLayout(LoaderLayout);
        LoaderLayout.setHorizontalGroup(
            LoaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );
        LoaderLayout.setVerticalGroup(
            LoaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(Loader2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Loader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Loader2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Loader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));

        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Account & Orders");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu2MouseEntered(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Manage Account");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Cart");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("My Orders");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("My Reviews");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("My WishList");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Need Help?");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Contact Us");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem8.setText("FAQs");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Exit");

        jMenuItem7.setText("Logout");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
CartBtn.setSelected(true);
        if(UID=="0"){//if guest user (Raffay)
            JOptionPane.showMessageDialog(null, "Login Required", "Error", JOptionPane.ERROR_MESSAGE);
                      this.setVisible(false);
                        li.setVisible(true);
        }else{
        Loader2.setVisible(true);
      jComboBox2.setVisible(false);
       jComboBox1.setVisible(false);
        load.jPanelLoader(Loader2, jPanel4);
         Cart cart =new Cart(UID);
        load.jPanelLoader(Loader, cart);
     }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
      
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      JOptionPane.showMessageDialog(this,
                "Contact us through email\nhuzaifaahmed5549@gmail.com",
                "Contact Us",
                JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
ManageAccountBtn.setSelected(true);
        if(UID=="0"){//if guest user (Raffay)
            JOptionPane.showMessageDialog(null, "Login Required", "Error", JOptionPane.ERROR_MESSAGE);
                      this.setVisible(false);
                        li.setVisible(true);
        }else{
        new ManageAccount(UID).setVisible(true);}
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
CartBtn.setSelected(true);
        if(UID=="0"){//if guest user (Raffay)
            JOptionPane.showMessageDialog(null, "Login Required", "Error", JOptionPane.ERROR_MESSAGE);
                      this.setVisible(false);
                        li.setVisible(true);
        }else{
        
        Loader2.setVisible(true);
      jComboBox2.setVisible(false);
       jComboBox1.setVisible(false);
        Cart cart =new Cart(UID);
        load.jPanelLoader(Loader2, jPanel4);
        load.jPanelLoader(Loader, cart);
    }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
MyOrderBtn.setSelected(true);
        if(UID=="0"){//if guest user (Raffay)
            JOptionPane.showMessageDialog(null, "Login Required", "Error", JOptionPane.ERROR_MESSAGE);
                      this.setVisible(false);
                        li.setVisible(true);
        }else{
        Loader2.setVisible(true);
  jComboBox2.setVisible(false);
       jComboBox1.setVisible(false);
        load.jPanelLoader(Loader2, jPanel4);
         MyOrders order=new MyOrders(UID);
         load.jPanelLoader(Loader, order);  
 }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
   MyReviews reviews =new MyReviews(UID);
        if(UID=="0"){//if guest user (Raffay)
            JOptionPane.showMessageDialog(null, "Login Required", "Error", JOptionPane.ERROR_MESSAGE);
                      this.setVisible(false);
                        li.setVisible(true);
        }else{  Loader2.setVisible(true);
            load.jPanelLoader(Loader2, jPanel4);
        load.jPanelLoader(Loader, reviews);
        jComboBox2.setVisible(false);
       jComboBox1.setVisible(false);}
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
      filter= jComboBox2.getSelectedItem().toString();
       HomePanel hp=new HomePanel(UID,Keyword,sort,filter);
       load.jPanelLoader(Loader, hp);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
MyWishListBtn.setSelected(true);
  MyWishList wishlist=new MyWishList(UID);
        if(UID=="0"){//if guest user (Raffay)
            JOptionPane.showMessageDialog(null, "Login Required", "Error", JOptionPane.ERROR_MESSAGE);
                      this.setVisible(false);
                        li.setVisible(true);
        }else  { 
            Loader2.setVisible(true);
            load.jPanelLoader(Loader2, jPanel4);
        load.jPanelLoader(Loader, wishlist); 
        jComboBox2.setVisible(false);
       jComboBox1.setVisible(false);}
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
       Loader2.setVisible(false);
         jComboBox2.setVisible(true);
       jComboBox1.setVisible(true);
       HomePanel HE=new HomePanel(UID,Keyword,sort,filter);
        load.jPanelLoader(Loader, HE);
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void ManageAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAccountBtnActionPerformed
        if(UID=="0"){//if guest user (Raffay)
            JOptionPane.showMessageDialog(null, "Login Required", "Error", JOptionPane.ERROR_MESSAGE);
                      this.setVisible(false);
                        li.setVisible(true);
        }else{
        new ManageAccount(UID).setVisible(true);
        }
    }//GEN-LAST:event_ManageAccountBtnActionPerformed

    private void CartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartBtnActionPerformed
       if(UID=="0"){//if guest user (Raffay)
            JOptionPane.showMessageDialog(null, "Login Required", "Error", JOptionPane.ERROR_MESSAGE);
                      this.setVisible(false);
                        li.setVisible(true);
        }else{
            Loader2.setVisible(true);
        load.jPanelLoader(Loader2, jPanel4);
        Cart cart =new Cart(UID);
        load.jPanelLoader(Loader, cart);
        
         jComboBox2.setVisible(false);
       jComboBox1.setVisible(false);}
    }//GEN-LAST:event_CartBtnActionPerformed

    private void MyOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyOrderBtnActionPerformed
MyOrderBtn.setSelected(true);     
        if(UID=="0"){//if guest user (Raffay)
            JOptionPane.showMessageDialog(null, "Login Required", "Error", JOptionPane.ERROR_MESSAGE);
                      this.setVisible(false);
                        li.setVisible(true);
        }else{   Loader2.setVisible(true);
  jComboBox2.setVisible(false);
       jComboBox1.setVisible(false);
        load.jPanelLoader(Loader2, jPanel4);
         MyOrders order=new MyOrders(UID);
         load.jPanelLoader(Loader, order);  }
    }//GEN-LAST:event_MyOrderBtnActionPerformed

    private void MyReviewsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyReviewsbtnActionPerformed
             MyReviews reviews =new MyReviews(UID);
        if(UID=="0"){//if guest user (Raffay)
            JOptionPane.showMessageDialog(null, "Login Required", "Error", JOptionPane.ERROR_MESSAGE);
                      this.setVisible(false);
                        li.setVisible(true);
        }else{  Loader2.setVisible(true);
            load.jPanelLoader(Loader2, jPanel4);
        load.jPanelLoader(Loader, reviews);
        jComboBox2.setVisible(false);
       jComboBox1.setVisible(false);}
    }//GEN-LAST:event_MyReviewsbtnActionPerformed

    private void MyWishListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyWishListBtnActionPerformed
  MyWishList wishlist=new MyWishList(UID);
        if(UID=="0"){//if guest user (Raffay)
            JOptionPane.showMessageDialog(null, "Login Required", "Error", JOptionPane.ERROR_MESSAGE);
                      this.setVisible(false);
                        li.setVisible(true);
        }else{ 
            Loader2.setVisible(true);
            load.jPanelLoader(Loader2, jPanel4);
        load.jPanelLoader(Loader, wishlist); 
        jComboBox2.setVisible(false);
       jComboBox1.setVisible(false);}
    }//GEN-LAST:event_MyWishListBtnActionPerformed

    private void Loader2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Loader2MouseClicked
     
    }//GEN-LAST:event_Loader2MouseClicked

    private void jPanel4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4FocusGained

    private void Loader2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Loader2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Loader2FocusGained

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
     if(jTextField2.getText().contains("Search"))
     { jTextField2.setText("");
     }
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
  Loader2.setVisible(false);
         jComboBox2.setVisible(true);
       jComboBox1.setVisible(true);
        Keyword= jTextField2.getText();
       HomePanel hp=new HomePanel(UID,Keyword,sort,filter);
       load.jPanelLoader(Loader, hp);
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      sort= jComboBox1.getSelectedItem().toString();
       HomePanel hp=new HomePanel(UID,Keyword,sort,filter);
       load.jPanelLoader(Loader, hp);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       int result = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to Logout?",
                "Exit Confirmation",
                JOptionPane.YES_NO_OPTION
        );

        if (result == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
      FAQs faq=new FAQs();
      faq.load();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseEntered
        
    }//GEN-LAST:event_jMenu2MouseEntered

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHomePage("5").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CartBtn;
    private javax.swing.JToggleButton HomeBtn;
    private javax.swing.JPanel Loader;
    private javax.swing.JPanel Loader2;
    private javax.swing.JToggleButton ManageAccountBtn;
    private javax.swing.JToggleButton MyOrderBtn;
    private javax.swing.JToggleButton MyReviewsbtn;
    private javax.swing.JToggleButton MyWishListBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
